services:
  - type: web
    name: kemri-lab-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn debug_app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: PYTHON_VERSION
        value: 3.9.16 