services:
  - type: web
    name: kemri-document-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.2
      - key: FLASK_APP
        value: app.py
      - key: FLASK_DEBUG
        value: 0 